name: stub-oidc-provider docker pipeline

on: [push]

env:
  image: docker.pkg.github.com/${{ github.repository }}/stub-oidc-provider

jobs:

  build:
    name: Build Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker image
        run: |
          docker build --tag ${image}:${GITHUB_SHA} --tag ${image}:latest .
      - name: Push Docker image
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${image}:${GITHUB_SHA}
          docker push ${image}:latest